//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using Newtonsoft.Json;

namespace System.ComponentModel
{
    internal class DataAnnotations
    {
        public class AdmUser
        {
            [JsonProperty("pKey")]
            Guid Pkey { get; set; }

            [JsonProperty("code")]
            string Code { get; set; }

            [JsonProperty("pass")]
            string pass { get; set; }

            [JsonProperty("description")]
            string Description { get; set; }

            [JsonProperty("userCreate")]
            string UserCreate { get; set; }

            [JsonProperty("userUpdate")]
            string UserUpdate { get; set; }

            [JsonProperty("emailPassword")]
            string EmailPassword { get; set; }

            [JsonProperty("emailSmtpserver")]
            string EmailSmtpserver { get; set; }

            [JsonProperty("openBeeCode")]
            string OpenBeeCode { get; set; }

            [JsonProperty("openBeePass")]
            string OpenBeePass { get; set; }
        }

        internal class RequiredAttribute : Attribute
        {
            public bool AllowEmptyStrings { get; set; }
        }

        internal class StringLengthAttribute : Attribute
        {
            public int Length { get; set; }
            public StringLengthAttribute(int i)
            {
                Length = i;
            }
        }
    }
}